/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.codigosecreto;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maximiliano Orellano
 */
public class NumeroSecreto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NumeroSecreto.class.getName());
    private Random random = new Random();
    private int ayudas = 0;
    private int intentos = 0;
    private int numeroRandom;
    /**
     * Creates new form NumeroSecreto
     */
    public NumeroSecreto() {
        initComponents();
        numeroRandom = random.nextInt(900) + 100;
        System.out.println(numeroRandom);
        psw1.setText(String.valueOf(String.valueOf(numeroRandom).charAt(0)));
        psw2.setText(String.valueOf(String.valueOf(numeroRandom).charAt(1)));
        psw3.setText(String.valueOf(String.valueOf(numeroRandom).charAt(2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkp = new javax.swing.JDesktopPane();
        lblPista = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtNumIngresado = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        lblImgTrofeo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        psw1 = new javax.swing.JPasswordField();
        psw2 = new javax.swing.JPasswordField();
        psw3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivina El numero secreto");

        lblPista.setForeground(new java.awt.Color(255, 255, 51));
        lblPista.setToolTipText("");
        lblPista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblTitulo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 51));
        lblTitulo.setText("Codigo Secreto");
        lblTitulo.setName(""); // NOI18N

        txtNumIngresado.setBackground(new java.awt.Color(255, 153, 153));
        txtNumIngresado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtNumIngresado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumIngresado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escribe 3 digitos + ENTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        txtNumIngresado.addActionListener(this::txtNumIngresadoActionPerformed);
        txtNumIngresado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumIngresadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumIngresadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumIngresadoKeyTyped(evt);
            }
        });

        btnMostrar.setText("Revelar");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        lblImgTrofeo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        psw1.setEditable(false);
        psw1.setBackground(new java.awt.Color(153, 153, 255));
        psw1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        psw1.setForeground(new java.awt.Color(204, 255, 153));
        psw1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psw1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psw1.addActionListener(this::psw1ActionPerformed);

        psw2.setEditable(false);
        psw2.setBackground(new java.awt.Color(255, 153, 153));
        psw2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        psw2.setForeground(new java.awt.Color(255, 255, 153));
        psw2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psw2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        psw3.setEditable(false);
        psw3.setBackground(new java.awt.Color(255, 255, 153));
        psw3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        psw3.setForeground(new java.awt.Color(153, 153, 255));
        psw3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psw3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psw3.addActionListener(this::psw3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(psw1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(psw2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(psw3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(psw1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(psw2)
                    .addComponent(psw3))
                .addGap(20, 20, 20))
        );

        dkp.setLayer(lblPista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp.setLayer(txtNumIngresado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp.setLayer(btnMostrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp.setLayer(lblImgTrofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dkpLayout = new javax.swing.GroupLayout(dkp);
        dkp.setLayout(dkpLayout);
        dkpLayout.setHorizontalGroup(
            dkpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpLayout.createSequentialGroup()
                .addGroup(dkpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dkpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dkpLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtNumIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(lblImgTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(dkpLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dkpLayout.setVerticalGroup(
            dkpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(dkpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpLayout.createSequentialGroup()
                        .addComponent(txtNumIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpLayout.createSequentialGroup()
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpLayout.createSequentialGroup()
                        .addComponent(lblImgTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkp)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psw1ActionPerformed

    private void txtNumIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIngresadoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        
        if(ayudas==0){
            psw1.setEchoChar((char)0);
            ayudas++;
        }else if(ayudas<2){
                psw2.setEchoChar((char)0);
                ayudas++;
            }else{
                JOptionPane.showMessageDialog(null, "No hay mas Ayudas");
            }
        
        
        
            // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtNumIngresadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIngresadoKeyReleased
        // TODO add your handling code here:
        if(txtNumIngresado.getText().length() != 3 || !txtNumIngresado.getText().matches("\\d+")){
            return;
        }
    }//GEN-LAST:event_txtNumIngresadoKeyReleased

    private void txtNumIngresadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIngresadoKeyTyped
        String input = txtNumIngresado.getText();
        input = input.trim();
        
        if(input.isEmpty() || !input.matches("\\d+")){
            return;
        }
        
        if(input.length() != 3){
            return;
        }
        int numeroIngresado = Integer.parseInt(input);
        
        if(numeroIngresado > numeroRandom){
            lblPista.setText("El numero secreto es menor a " + numeroIngresado);
            txtNumIngresado.setText("");
        }else if(numeroIngresado < numeroRandom){
            lblPista.setText("El numero secreto es mayor a " + numeroIngresado);
            txtNumIngresado.setText("");
        }else{
            lblPista.setText("¡Acertaste el numero secreto!");
        }
    }//GEN-LAST:event_txtNumIngresadoKeyTyped

    private void txtNumIngresadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIngresadoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String input = txtNumIngresado.getText();
            
            if(input.isEmpty() || !input.matches("\\d+")){
                return;
            }
            int numeroIngresado = Integer.parseInt(input);
            intentos++;
            
            if(numeroIngresado == numeroRandom){
                psw1.setEchoChar((char)0);
                psw2.setEchoChar((char)0);
                psw3.setEchoChar((char)0);
                try {
                    URL url = new URL("https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png");
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                    lblImgTrofeo.setIcon(new ImageIcon(img));
                } catch (Exception ex){
                    System.out.println("Error al cargar la imagen: " + ex.getMessage());
                }
                
                JDialog dialogoGanar = new JDialog(this,"¡Victoria!",true);
                dialogoGanar.setSize(250, 150);
                dialogoGanar.setLayout(new java.awt.FlowLayout());
                dialogoGanar.add(new JLabel("¡Ganaste!"));
                dialogoGanar.add(new JLabel("Código Correcto: " + numeroRandom));
                dialogoGanar.add(new JLabel("Intentos Totales: " + intentos));
                dialogoGanar.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtNumIngresadoKeyPressed

    private void psw3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psw3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NumeroSecreto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JDesktopPane dkp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImgTrofeo;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField psw1;
    private javax.swing.JPasswordField psw2;
    private javax.swing.JPasswordField psw3;
    private javax.swing.JTextField txtNumIngresado;
    // End of variables declaration//GEN-END:variables
}
